#!/usr/bin/env python3

import docker, sys

if len(sys.argv) < 2:
    print("please set the cmd")
    exit()
cmd = sys.argv[1]

cli = docker.from_env()
for each in cli.volumes.list():
    print("image: " + each.name)
    ret = cli.containers.run('alpine', cmd, remove=True, volumes={each.name:{'bind':'/data'}})
    lines = ret.decode('utf-8').split('\n')
    for line in lines:
        print(line)
